server:
  port: 8080

spring:
  application:
    name: "device-ms"
  datasource:
    url: "jdbc:mysql://localhost:3306/device_db"
    username: "root"
    password: "root"
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
